config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :todo_lists do
  	resources :todo_items do
  		member do
  			patch :complete
  		end
  	end
  end

  root "todo_lists#index"

  namespace 'api' do
    namespace 'v1' do
      resources :sessions, only: [:create, :destroy]
      resources :articles
    end
  end
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  def completed?
  	!completed_at.blank?
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
	before_action :set_todo_list
	before_action :set_todo_item, except: [:create]

def create
	@todo_item = @todo_list.todo_items.create(todo_item_params)
	redirect_to @todo_list
end

def destroy
	@todo_item = @todo_list.todo_items.find(params[:id])
	if @todo_item.destroy
		flash[:success] = "Todo List item was deleted."
	else
		flash[:error] = "Todo List item could not be deleted."
	end
	redirect_to @todo_list 
end

def complete
	@todo_item.update_attribute(:completed_at, Time.now)
	redirect_to @todo_list, notice: "Todo item completed"
end

private

def set_todo_list
	@todo_list = TodoList.find(params[:todo_list_id])
end

def set_todo_item
	@todo_item = @todo_list.todo_items.find(params[:id])
end

def todo_item_params
	params[:todo_item].permit(:content)
end 

end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
	<%= f.text_field :content, placeholder: "New Todo" %>
	<%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<!--- 
<p><%= todo_item.content %></p>
<%= link_to "Delete", todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } %>
<%= link_to "Mark as Complete", complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch %>
-->

<div class="row clearfix">
	<% if todo_item.completed? %>
		<div class="complete">
			<%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
				<i style="opacity: 0.4;" class="fa fa-check"></i>
			<% end %>
		</div>
		<div class="todo_item">
			<p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
		</div>
		<div class="trash">
			<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>
	<% else %>
		<div class="complete">
			<%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
				<i class="fa fa-circle-thin"></i>
			<% end %>
		</div>
		<div class="todo_item">
			<p><%= todo_item.content %></p>
		</div>
		<div class="trash">
			<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>
	<% end %>
</div>