config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :todo_lists do
  	resources :todo_items do
  		member do
  			patch :complete
  		end
  	end
  end

  root "todo_lists#index"

  namespace 'api' do
    namespace 'v1' do
      resources :sessions, only: [:create, :destroy]
      resources :articles
    end
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
	has_many :todo_items
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  #skip_before_action :authenticate_user!, :only => [:index]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :todo_list_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :todo_list_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Editing Todo List</h1>

<div class="forms">
<%= render 'form', todo_list: @todo_list %>
</div>

<div class="links">
<%= link_to 'Cancel', todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<% @todo_lists.each do |todo_list| %>
<div class="index_row clearfix">
  <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
  <p class="todo_list_sub_title"><%= todo_list.description %></p>
</div>
<% end %>

<div class="links">
  <h1><%= link_to "New Todo List after CI/CD setup Date 03-07-2018", new_todo_list_path %></h1>
</div>

app/views/todo_lists/new.html.erb
<h1 class="todo_list_title">New Todo List</h1> 

<div class="forms">
<%= render 'form', todo_list: @todo_list %>
</div>

<div class="links">
<%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="todo_list_title"><%= @todo_list.title %></h2>
<p class="todo_list_sub_title"><%= @todo_list.description %></p>

<!-- WE DONT NEED ANYMORE!
<p>
  <strong>Title:</strong>
  <%= @todo_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_list.description %>
</p>
-->

<div id="todo_items_wrapper">
	<%= render @todo_list.todo_items %>
	<div id="form">
		<%= render "todo_items/form" %>
	</div>
</div>

<div class="links">
	<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
	<%= link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" } %> |
	<%= link_to 'Back', todo_lists_path %>
</div>